djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject import settings
from listing.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('listing/', include('listing.urls')),
    path('order/', include('order.urls')),
    path('metrics/', include('metrics.urls')),
    path('chatroom/', include('live_chat.urls')),
    path('', HomeView.as_view(), name='home'),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('change-password/', views.MyPasswordChangeView.as_view(), name='change_password'),
    path('profile/', views.edit_profile, name='profile'),
]

listing/models.py
from PIL import Image, ImageOps
from django.core.files import File
from django.core.validators import MinValueValidator
from django.db import models

from user.models import CustomUser, City


class Category(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ListingType(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Photo(models.Model):
    listing = models.ForeignKey('Listing', related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='listing_images', null=True, blank=True)
    image_thumbnail = models.ImageField(upload_to='listing_images/thumbnails', null=True, blank=True)

    def resize_image_to_16_9(self, image_field, is_thumbnail=True, output_size=None):
        THUMBNAIL_SIZE = (320, 180)  # for 16:9
        MAIN_IMAGE_SIZE = (1920, 1080)  # for 16:9

        with Image.open(image_field.path) as original:
            width, height = original.size
            target_ratio = 16 / 9
            current_ratio = width / height

            # Image is portrait or square
            if current_ratio <= 1:
                target_width = int(height * target_ratio)
                padding = (target_width - width) // 2
                result = ImageOps.expand(original, (padding, 0, padding, 0), fill='white')

            # Image is landscape
            else:
                # If already 16:9
                if current_ratio == target_ratio:
                    result = original

                # Wider than 16:9
                elif current_ratio > target_ratio:
                    target_height = int(width / target_ratio)
                    padding = (target_height - height) // 2
                    result = ImageOps.expand(original, (0, padding, 0, padding), fill='white')

                # Narrower than 16:9
                else:
                    target_width = int(height * target_ratio)
                    left = (width - target_width) // 2
                    right = left + target_width
                    result = original.crop((left, 0, right, height))

            if not output_size:
                output_size = THUMBNAIL_SIZE if is_thumbnail else MAIN_IMAGE_SIZE

            result = result.resize(output_size, Image.LANCZOS)
            result.save(image_field.path)

    def save(self, *args, **kwargs):
        # Check if the image exists before processing
        if self.image and hasattr(self.image, 'path'):
            # First, save the original image without processing
            super().save(*args, **kwargs)

            # Store the original image path for further processing
            original_image_path = self.image.path

            # Process the main image to 16:9 from the original image
            self.resize_image_to_16_9(self.image, is_thumbnail=False)
            super().save(*args, **kwargs)  # Save the main image after processing

            # Process the thumbnail using the original image
            with open(original_image_path, 'rb') as original_image_file:
                # Attach the original image file to the thumbnail field
                self.image_thumbnail.save(self.image.name, File(original_image_file), save=False)
                self.resize_image_to_16_9(self.image_thumbnail, is_thumbnail=True)
            super().save(*args, **kwargs)  # Save the thumbnail after processing
        else:
            super().save(*args, **kwargs)

    def __str__(self):
        return self.listing.name


class Condition(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class MeetupPoint(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Listing(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    listing_type = models.ForeignKey(ListingType, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=500)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='listings')
    condition = models.ForeignKey(Condition, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0.00)], default=0.00)
    meetup_available = models.BooleanField(default=False)
    meetup_point = models.ForeignKey(MeetupPoint, on_delete=models.CASCADE, null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, default=1)
    created_date = models.DateTimeField(auto_now_add=True)

templates/base.html
{% load django_bootstrap5 %}
{% load django_bootstrap5 %}
{% load django_bootstrap5 %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>On Your Mart, On Your Mark</title>

    <!-- Google Fonts API -->
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap" rel="stylesheet">

    <!-- Link to page favicon.png to display in the location bar -->
    <link rel="icon" href="{% static 'image/favicon.png' %}">

    <!-- Font Awesome CSS -->
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Jquery JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- ECharts JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.4.3/echarts.min.js"></script>

</head>
<body>
<div class="wrapper">
    <!-- Common header or navigation -->
    <nav class="navbar navbar-expand-lg navbar-light custom-nav">
        <div class="container-fluid">

            <!-- Navbar Brand -->
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'image/logo.png' %}" alt="logo" width="79" height="60">
            </a>

            <!-- Centered Search Bar and Button -->
            <div class="search-bar">
                <form class="input-group" action="{% url 'search_listing' %}" method="get">
                    <input class="form-control" type="search" placeholder="Search for listings..."
                           aria-label="Search" name="query" value="{{ request.GET.query }}">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>

            <!-- Right-aligned Navigation Options -->
            <div class="ml-auto">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle btn edu-function" href="#" id="recycleNowDropdown"
                           data-bs-toggle="dropdown">
                            Recycle Now
                        </a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="recycleNowDropdown">
                            <a class="dropdown-item" href="{% url 'redirect_recycle_an_item' %}" target="_blank">Recycle
                                an Item</a>
                            <a class="dropdown-item" href="{% url 'redirect_recycling_locator' %}" target="_blank">Recycling
                                Locator</a>
                            <a class="dropdown-item" href="{% url 'redirect_how_to_recycle' %}" target="_blank">How to
                                Recycle</a>
                        </div>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'kpi_overview' %}">
                            <button class="btn edu-function">Metrics Overview</button>
                        </a>
                    </li>

                    {% if user.is_authenticated %}
                        <!-- Create Listing -->
                        <li>
                            <a class="nav-link" href="{% url 'create_listing' %}">
                                <button class="btn btn-eye-catching">
                                    <i class="fa-solid fa-upload"></i>
                                    Listing
                                </button>
                            </a>
                        </li>
                        <!-- Combined Chat with Notification Badge -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'chatroom_without_id' %}">
                                <i class="fa-regular fa-envelope"></i>
                                <span class="notification-badge" id="message-notification-badge">0</span>
                            </a>
                        </li>

                        <!-- User Profile Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="hello-btn nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                               data-bs-toggle="dropdown">
                                {% if user.avatar %}
                                    <!-- Display user avatar if exists -->
                                    <img src="{{ user.avatar.url }}" alt="avatar" class="avatar-img small-avatar">
                                {% else %}
                                    <!-- Display default icon if no avatar -->
                                    <i class="fas fa-user-circle" style="font-size: 33px;"></i>
                                {% endif %}
                            </a>

                            <!-- Dropdown Menu Items -->
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'kpi_user' %}"> Listing Insight</a>
                                {#                                <a class="dropdown-item" href="{% url 'listing_dashboard' %}">Listings</a>#}
                                <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                                <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </li>
                    {% else %}
                        <!-- Unauthenticated User Options -->
                        <li>
                            <a class="nav-link" href="{% url 'login' %}">
                                <button class="btn btn-eye-catching">
                                    <i class="fas fa-upload"></i> Listing
                                </button>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">
                                <button class="btn btn-primary">Register | Login</button>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Categories Dropdown -->
    <nav class="navbar navbar-expand-lg navbar-light custom-dropdown-menu">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#categoriesNavbar"
                    aria-controls="categoriesNavbar" aria-expanded="false" aria-label="Toggle navigation">
                Categories
            </button>
            <div class="collapse navbar-collapse" id="categoriesNavbar">
                <ul class="navbar-nav">
                    {% for category in categories %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink_{{ category.name }}"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                {{ category.name }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink_{{ category.name }}">
                                {% for subcategory in category.category_set.all %}
                                    <li class="dropdown-submenu">
                                        <a class="dropdown-item" href="#">{{ subcategory.name }}</a>
                                        <ul class="dropdown-menu">
                                            {% for subsubcategory in subcategory.category_set.all %}
                                                <li><a class="dropdown-item" href="#">{{ subsubcategory.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Main content -->
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <hr>
        <p class="text-center"> | University of Birmingham | &copy; On Your Mart | 2022-2023 MSc Project |</p>
    </footer>
</div>
<script>
    function showDropDown() {
        // Show the dropdown on hover
        $(".hello-btn").hover(function () {
            $(this).dropdown('toggle');
        });
    }

    function fetchUnreadMessagesCount() {
        const url = '/chatroom/unread-messages-count/';
        console.log("Fetching from:", url);

        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                const badge = document.getElementById('message-notification-badge');
                badge.textContent = data.unread_count;
                badge.setAttribute('data-count', data.unread_count);
            })
            .catch(e => {
                console.log('Fetch failed', e);
            });
    }

    // Now, call this function
    fetchUnreadMessagesCount();
    setInterval(fetchUnreadMessagesCount, 10000);  // Check every 10 seconds

    function markChatRoomAsRead(roomIdentifier) {
        const url = `/mark_chat_room_messages_as_read/${roomIdentifier}/`;

        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                fetchUnreadMessagesCount();  // Fetch updated unread count
            })
            .catch(e => {
                console.log('Fetch failed', e);
            });
    }

</script>
</body>
</html>